### ISSUE TITLE
Calls.js: support the `streaming_start` and `streaming_stop` commands

### ISSUE THREAD

**Issue by slapierre** [team-telnyx/telnyx-node#139]
**Feature request**: add the `streaming_start` and `streaming_stop` commands in the `CALL_COMMANDS` array of [Calls.js](https://github.com/team-telnyx/telnyx-node/blob/master/lib/resources/Calls.js#L7-L31).

**Proposal**: opened PR #140.

We forked the [telnyx-node](https://github.com/team-telnyx/telnyx-node) repo to add the commands and then modified our app using the [Call Commands](https://developers.telnyx.com/docs/api/v2/call-control/Call-Commands) documentation, we were able to successfully stream the media from a call. 

I noticed 2 issues with the build:

1. ESLint reports a double-quoted string in [express.js](https://github.com/team-telnyx/telnyx-node/blob/master/examples/webhook-signing/express.js#L95): can be fixed easily with `npm run lint -- --fix` 
1. The GitHub CI fails to run:

    <img src="https://user-images.githubusercontent.com/11460109/197809455-85078b72-3831-4341-8caa-d9b48b0f2250.png" width="45%" height="45%">

For item (2) I am experiencing the same output as in the GitHub Action when trying to run `npm test` locally -- note that I followed the instructions in the README.md to install and run Prism.

**Comment by vionash** [comment]
This should be implemented in the newest update

The quoting error should be resolved as well in the latest update. Start another issue if there's anything else, thanks for your feedback from above! 
(The tests should also now work correctly)
