### ISSUE TITLE
Update the uglify-js dependency to 2.4.24

### ISSUE THREAD

**Issue by prince76007** [team-telnyx/telnyx-node#152]
The uglify-js package before 2.4.24 for Node.js does not properly account for non-boolean values when rewriting boolean expressions, which might allow attackers to bypass security mechanisms or possibly have unspecified other impacts by leveraging improperly rewritten Javascript.

package name: uglify-js

fixed version: 2.4.24

**Comment by vionash** [comment]
Resolved in the last update
