### ISSUE TITLE
unable to install library

### ISSUE THREAD

**Issue by mudi256** [team-telnyx/telnyx-node#7]
i'm facing issues, when try to install telnyx library with "npm install telnyx --save " please check the below attachment
<img width="1440" alt="Screenshot 2019-09-01 at 6 05 49 PM" src="https://user-images.githubusercontent.com/36504724/64076999-34632280-cce5-11e9-9eba-dba9352cdf55.png">

**Comment by lucasassisrosa** [comment]
Hello @mudi256,

It seems it's an error with our lib on node v12 (due to the `ed25519` lib we're using now). 

If you could please use node v10 or lower (even versions), it should work fine. There's a PR open to fix for v12 #8

**Comment by lucasassisrosa** [comment]
@mudi256 this should be fixed now on [v1.2.1](https://github.com/team-telnyx/telnyx-node/releases/tag/v1.2.1)
