### ISSUE TITLE
Signature is invalid for receiving webhooks

### ISSUE THREAD

**Issue by alechirsch** [team-telnyx/telnyx-node#81]
Node Version: 12.13.0
package version: 1.17.0

Attempting to verify the signature on a webhook but getting 'Signature is invalid and does not match the payload' error. I am using express and need the json body as well as the raw body so I did this, which does give a proper result:
```
const app = express();
app.use(bodyParser.json({
	limit: '100mb',
	verify(req, res, buffer) {
		req.rawBody = buffer;
	}
}));
```

In the webhook endpoint, I do this: 
```
let telnyx = new Telnyx(TELNYX_API_KEY);
let verifiedRequest = telnyx.webhooks.constructEvent(
	req.rawBody,
	req.header('telnyx-signature-ed25519'),
	req.header('telnyx-timestamp'),
	TELNYX_PUBLIC_KEY
);
```

rawBody is a buffer, I stepped through the constructEvent function and everything looked fine. The stringified version of rawBody is this (replaced information with "hidden"):
```
{
  "data": {
    "event_type": "fax.queued",
    "id": "hidden",
    "occurred_at": "2021-07-21T19:52:26.765917Z",
    "payload": {
      "connection_id": "hidden",
      "direction": "outbound",
      "fax_id": "hidden",
      "from": "hidden",
      "original_media_url": "hidden",
      "status": "queued",
      "to": "hidden",
      "user_id": "hidden"
    },
    "record_type": "event"
  },
  "meta": {
    "attempt": 1,
    "delivered_to": "hidden"
  }
}
```

I am at a loss for what the problem could be.

**Comment by szajbus** [comment]
Hi, I tried using your code above as well as [example code from this repository](https://github.com/team-telnyx/telnyx-node/tree/master/examples/webhook-signing), and could not reproduce the error.

You're right that rawBody buffer should work just fine, it is converted to string under the hood.

Could you double check that 
* API key is correct and active
* Public key is correct
* both keys belong to the same account as your Programmable Fax application

**Comment by alechirsch** [comment]
I have triple checked the API key and Public key, although I do not see how the API key ties into this since you only need the public key for the verification. I have also tried to verify through nodes own crypto library with no success. Perhaps the public key given to me in the Telnyx UI is incorrect?

**Comment by szajbus** [comment]
That's true, the only thing needs to verify the signature is the public key.

Since the public key is correct, my only suspicion  would be that maybe the payload itself is modified in some way before it reaches the application or the handler function, possibly by some middleware or proxy.

Are you able to replicate the behaviour in other environments?

**Comment by alechirsch** [comment]
I am now doing exactly what the example does and it still fails
```
let verifiedRequest = telnyx.webhooks.constructEvent(
	JSON.stringify(req.body, null, 2),
	req.header('telnyx-signature-ed25519'),
	req.header('telnyx-timestamp'),
	TELNYX_PUBLIC_KEY
);
```

Could there be an issue with the signing? Perhaps the wrong key is being used to sign?

I am able grab the body/headers and attempt to verify the signature locally with no success

**Comment by bluesbettle** [comment]
@alechirsch this has been an issue on our side. This has been fixed already, can you verify on your end?

**Comment by alechirsch** [comment]
@bluesbettle Thats for the update, I will test this soon

**Comment by alechirsch** [comment]
@bluesbettle Finally got around to testing this, look good on my end. Thanks!
