### ISSUE TITLE
SDK not matching docs

### ISSUE THREAD

**Issue by elhe26** [team-telnyx/telnyx-node#96]
Hi guys,

I'm trying to use the sdk but I'm having this error: "Unresolved variable messagingProfiles."

Regards,

**Comment by elhe26** [comment]
Any updates?

**Comment by Kashalls** [comment]
> Hi guys,
> 
> I'm trying to use the sdk but I'm having this error: "Unresolved variable messagingProfiles."
> 
> Regards,

Where are you getting this error?

**Comment by vionash** [comment]
Setting this as resolved, if you're having trouble feel free to open another issue and link where you are having trouble resolving the messageProfiles. Thanks
